// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20251211140417_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "Photo",
                            Description = "Foto com logo Geek",
                            ImageURL = "",
                            Name = "Geek Picture",
                            Price = 10.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Material Escolar",
                            Description = "NoteBook com logo Geek",
                            ImageURL = "",
                            Name = "Geek NoteBook",
                            Price = 49.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Vestuario",
                            Description = "Escova com logo Geek",
                            ImageURL = "",
                            Name = "Geek Brush",
                            Price = 15.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Alimento",
                            Description = "Bolo com logo Geek",
                            ImageURL = "",
                            Name = "Geek Cake",
                            Price = 12.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Vestuario",
                            Description = "Oculos com logo Geek",
                            ImageURL = "",
                            Name = "Geek Glass",
                            Price = 90.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Vestuario",
                            Description = "Bermuda com logo Geek",
                            ImageURL = "",
                            Name = "Geek Short",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Vestuario",
                            Description = "Luvas com logo Geek",
                            ImageURL = "",
                            Name = "Geek Gloves",
                            Price = 20.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Vestuario",
                            Description = "Bone com logo Geek",
                            ImageURL = "",
                            Name = "Geek Hat",
                            Price = 69.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
